repos:
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 0839f92796ae388643a08a21640a029b322be5c2  # frozen: v0.15.2
    hooks:
    - id: ruff
      args:
      - --select
      - F401
      - --fix
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 0839f92796ae388643a08a21640a029b322be5c2  # frozen: v0.15.2
    hooks:
    - id: ruff
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 0839f92796ae388643a08a21640a029b322be5c2  # frozen: v0.15.2
    hooks:
    - id: ruff-format
# -
    # repo: local
    # hooks:
    # -   id: mypy
    #     args:
    #     - --show-error-codes
    #     name: mypy
    #     entry: poetry run mypy
    #     require_serial: true
    #     language: system
    #     exclude: ^tests/|^migrations/|^api_client/
    #     types:
    #     - python
-   repo: https://github.com/commitizen-tools/commitizen
    rev: 7179a42b3544e953e3683a670056ad385892365d  # frozen: v4.13.8
    hooks:
    -   id: commitizen
        stages:
        - commit-msg
