FROM python:3.11-slim-bullseye

# Set the working directory in the container
WORKDIR /app


# Install Poetry
ENV POETRY_VERSION=1.8.1
RUN pip install "poetry==$POETRY_VERSION"

# Copy the Poetry configuration files
COPY pyproject.toml poetry.lock ./
# Install project dependencies
RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi --no-root


# Copy the rest of the application code
COPY . .

# Set the entrypoint script
CMD ["bash"]